using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KCICApprovalQueue.Data;
using KCICApprovalQueue.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace KCICApprovalQueue.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ClaimsController : ControllerBase
    {
        ///// <summary>
        ///// Protected endpoint for creating new Claim records
        ///// </summary>
        ///// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "submitter")]
        public IActionResult Post([FromBody]ClaimDataModel model)
        {
            //Inject date submitted & submitted by
            model.DateSubmitted = DateTime.Now;
            model.SubmittedBy = User.Identity.Name;

           

            //Persist the new claim
            ClaimsRepository.Insert(model);

            //Return the model that now has an autogenerated GUID
            return Ok(model);
        }

        /// <summary>
        /// REST endpoint for getting all claims in queue
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Get()
        {
            try
            {
                return Ok(ClaimsRepository.GetAll());
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex);
            }
        }
        [Route("delete/{id}")]
        [HttpGet]
        public IActionResult RemoveClaim(Guid id)
        {
            Console.WriteLine("Endpoint Called");
            ClaimsRepository.Delete(id);
            return Ok("Removed");
        }

    }
}